<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_artist-header-options',
		'title' => 'Artist Header Options',
		'fields' => array (
			array (
				'key' => 'field_559862effac1f',
				'label' => 'Artist Statement',
				'name' => 'artist_statement',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_55986321fac21',
				'label' => 'Curator Statement',
				'name' => 'curator_statement',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_55986333fac22',
				'label' => 'Zing Magazine Links',
				'name' => 'zing_links',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5598634dfac23',
						'label' => 'Link Text',
						'name' => 'text',
						'type' => 'text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55986370fac24',
						'label' => 'Link URL',
						'name' => 'url',
						'type' => 'text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Link',
			),
			array (
				'key' => 'field_5598639dfac25',
				'label' => 'Artist Site URL',
				'name' => 'artist_site_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_559863cbfac26',
				'label' => 'Artist Galleries',
				'name' => 'artist_galleries',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_559863f2fac27',
						'label' => 'Gallery Slides:',
						'name' => 'slides',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55986416fac28',
								'label' => 'Slide Image',
								'name' => 'image',
								'type' => 'image',
								'required' => 1,
								'column_width' => '',
								'save_format' => 'id',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_55986456fac29',
								'label' => 'Slide Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55986463fac2a',
								'label' => 'Slide Caption',
								'name' => 'caption',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'basic',
								'media_upload' => 'no',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add Slide',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Gallery',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'artist',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
